server:
  port: 80
spring:
  session:
    store-type: redis
    timeout: "3600"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  redis:
    host: 46.55.144.22
    port: 3679
    password: redis
    timeout: 60000
    jedis:
      pool:
        # 最大连接数（负数表示没有限制）
        max-active: 8
        # 最大空闲连接
        max-idle: 8
        # 最小空闲链接
        min-idle: 0
        # 最大阻塞等待时间（负数表示没有限制）
        max-wait: -1
  thymeleaf:
    cache: false
    cache-period: 0
  datasource:
    url: jdbc:mysql://46.55.144.22:3306/java?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    favicon:
      enabled: false